version: '3.8'
services:
  mysql:
      image: mysql:5.7
      container_name: mysql-container
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: "12344321"
        MYSQL_DATABASE: "DBMS_project"
      ports:
        - "3307:3306"
      volumes:
        - mysql-data:/var/lib/mysql
      networks:
        - internalnetwork

  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
        DB_HOST: "mysqldb"
        DB_PORT: 3306
        DB_USER: "root"
        DB_PASSWORD: "samar"
        DB_NAME: "cs260"
    networks:
      - internalnetwork

  
networks:
 internalnetwork:
  driver: bridge
volumes:
  mysql-data:
